/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

import com.flujos.Utilidades.Conexion;
import com.flujos.Utilidades.Utilidades;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author monse
 */
public class FrmABMChequeTerceros extends javax.swing.JFrame {

    private Conexion con;

    /**
     * Creates new form FrmABMChequeTerceros
     */
    public FrmABMChequeTerceros() {
        try {
            initComponents();

            inicializar();
        } catch (SQLException ex) {

            Utilidades.msg(null, "Error al inicializar la ventana");
            this.dispose();
        }
    }

    private void inicializar() throws SQLException {

        con = new Conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        TxtNumero = new javax.swing.JTextField();
        lblNumCheque = new javax.swing.JLabel();
        lblImporteCheque = new javax.swing.JLabel();
        TxtImporteCheque = new javax.swing.JTextField();
        lblFechaCobro = new javax.swing.JLabel();
        jDateFechaCobro = new com.toedter.calendar.JDateChooser();
        lblObservacionCheque = new javax.swing.JLabel();
        TxtObservacionCheque = new javax.swing.JTextField();
        lblTitularCheque = new javax.swing.JLabel();
        comboTitularCheque = new javax.swing.JComboBox<>();
        TxtIdTitularCheque = new javax.swing.JTextField();
        TxtIdChequeTercero = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JToggleButton();
        btnModificar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");

        lblNumCheque.setText("Numero de Cheque:");

        lblImporteCheque.setText("Importe Cheque:");

        lblFechaCobro.setText("Fecha de cobro:");

        lblObservacionCheque.setText("Observacion Cheque:");

        lblTitularCheque.setText("Titular Cheque:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumCheque)
                            .addComponent(lblFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObservacionCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitularCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtObservacionCheque)
                                    .addComponent(comboTitularCheque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtImporteCheque)
                                    .addComponent(jDateFechaCobro, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBuscar)
                                .addGap(123, 123, 123)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtIdChequeTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIdTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(TxtIdChequeTercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumCheque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImporteCheque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFechaCobro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtObservacionCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObservacionCheque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitularCheque))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (TxtNumero.getText().equals("")) {
            Utilidades.msg(null, "El numero del cheque no puede estar vacio");
            TxtNumero.requestFocus();
            return;
        }

        if (Utilidades.isNunInt(TxtNumero.getText()) && !(Long.parseLong(TxtNumero.getText()) > 0)) {
            Utilidades.msg(null, "Numero incorrecto");
            TxtNumero.setText("");
            TxtNumero.requestFocus();
            return;
        }

        if (TxtImporteCheque.getText().equals("")) {
            Utilidades.msg(null, "El importe no puede estar vacio");
            TxtImporteCheque.requestFocus();
            return;
        }

        if (!Utilidades.isValidBigDecimal(TxtImporteCheque.getText())) {
            Utilidades.msg(null, "Importe incorrecto");
            TxtImporteCheque.setText("");
            TxtImporteCheque.requestFocus();
            return;
        }

        if (jDateFechaCobro.getDate() == null) {
            Utilidades.msg(null, "Ingrese una fecha de cobro");
            jDateFechaCobro.setDate(null);
            jDateFechaCobro.requestFocus();
            return;
        }

        if (comboTitularCheque.getSelectedItem().equals("--")) {
            Utilidades.msg(null, "Debe seleccionar un titular para el cheque");
            comboTitularCheque.requestFocus();
            return;
        }

        if (Utilidades.existe(con.getConexion(), "SELECT (1) FROM cheque_tercero WHERE nro_cheque = " + Long.parseLong(TxtNumero.getText()) + " ")) {
            Utilidades.msg(null, "No se puede ingresar porque el numero de cheque ya existe");
            TxtNumero.setText("");
            TxtIdTitularCheque.setText("");
            TxtImporteCheque.setText("");
            TxtObservacionCheque.setText("");
            comboTitularCheque.setSelectedIndex(0);
            jDateFechaCobro.setDate(null);
            TxtIdChequeTercero.setText("");
        } else {
            try {

                String sql = "INSERT INTO cheque_tercero (nro_cheque, id_titular, importe, fecha_cobro, observacion) "
                        + "VALUES (?, ?, ?, ?, ?)";
                PreparedStatement ps = con.getConexion().prepareStatement(sql);

                // Setear valores
                ps.setLong(1, Long.parseLong(TxtNumero.getText()));
                ps.setInt(2, Integer.parseInt(TxtIdTitularCheque.getText()));
                ps.setBigDecimal(3, new BigDecimal(TxtImporteCheque.getText()));
                ps.setDate(4, new java.sql.Date(jDateFechaCobro.getDate().getTime()));
                ps.setString(5, TxtObservacionCheque.getText());

                // Ejecutar
                ps.executeUpdate();

                // Confirmación
                Utilidades.msg(null, "Cheque agregado correctamente");

                // Limpiar campos
                TxtNumero.setText("");
                TxtIdTitularCheque.setText("");
                TxtImporteCheque.setText("");
                TxtObservacionCheque.setText("");
                comboTitularCheque.setSelectedIndex(0);
                jDateFechaCobro.setDate(null);
            } catch (SQLException e) {
                Utilidades.msg(null, "Error al guardar el cheque: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        //aca limpio
        TxtNumero.setText("");
        TxtIdTitularCheque.setText("");
        TxtImporteCheque.setText("");
        TxtObservacionCheque.setText("");
        comboTitularCheque.setSelectedIndex(0);
        jDateFechaCobro.setDate(null);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (TxtNumero.getText().equals("")) {
            Utilidades.msg(null, "Ingrese el número del cheque a eliminar");
            return;
        }

        try {

            //corfirmar
            if (!Utilidades.existe(con.getConexion(), "SELECT 1 FROM cheque_tercero WHERE nro_cheque = " + TxtNumero.getText())){
                Utilidades.msg(null, "El cheque no existe:");
                return;
            }
            
            //confirmacion
            int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar este cheque?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION
            );
            
            
            if(opcion == JOptionPane.YES_OPTION){
                String sql = "DELETE FROM cheque_tercero WHERE nro_cheque = ?";
                PreparedStatement ps = con.getConexion().prepareStatement(sql);
                ps.setLong(1, Long.parseLong(TxtNumero.getText()));
                ps.executeUpdate();
                
                Utilidades.msg(null, "cheque eliminado correctamente");
                
                
                //limpiar campos
                TxtNumero.setText("");
                TxtIdTitularCheque.setText("");
                TxtImporteCheque.setText("");
                TxtObservacionCheque.setText("");
                comboTitularCheque.setSelectedIndex(0);
                jDateFechaCobro.setDate(null);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            Utilidades.msg(null, "Error al eliminar el cheque: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmABMChequeTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmABMChequeTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmABMChequeTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmABMChequeTerceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmABMChequeTerceros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtIdChequeTercero;
    private javax.swing.JTextField TxtIdTitularCheque;
    private javax.swing.JTextField TxtImporteCheque;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtObservacionCheque;
    private javax.swing.JToggleButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JToggleButton btnModificar;
    private javax.swing.JToggleButton btnSalir;
    private javax.swing.JComboBox<String> comboTitularCheque;
    private com.toedter.calendar.JDateChooser jDateFechaCobro;
    private javax.swing.JLabel lblFechaCobro;
    private javax.swing.JLabel lblImporteCheque;
    private javax.swing.JLabel lblNumCheque;
    private javax.swing.JLabel lblObservacionCheque;
    private javax.swing.JLabel lblTitularCheque;
    // End of variables declaration//GEN-END:variables
}
