/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

import com.flujos.DAOs.DAOFlujosMov;
import com.flujos.Utilidades.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class FrmBajaFlujosMov extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBajaFlujosMov.class.getName());

    private Conexion con;

    private DefaultTableModel modelTblResultado = new DefaultTableModel();

    private DAOFlujosMov daoFlujosMov;

    /**
     * Creates new form FrmBajaFlujosMov
     */
    public FrmBajaFlujosMov() {
        initComponents();
        crearModeloTabla();
        inicializar();
    }

    private void crearModeloTabla() {
        modelTblResultado = (new DefaultTableModel(null,
                //Títulos    
                new String[]{"Movimiento", "Concepto", "Importe", "Observaciones", "ID", "Ref Cheque Propio", "Ref Cheque tercero"}) {

            //Celdas editables
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return canEdit[colIndex];
            }

        });
    }

    private void limpiarTabla() {
        txtIDFlujoMov.setText("");
        txtIdChequePropio.setText("");
        txtIdChequeTercero.setText("");

        for (int i = 0; i < tblResultados.getRowCount(); i++) {
            modelTblResultado.removeRow(i);
            i -= 1;
        }
    }

    private void seleccionarResultado() {

        int fila = tblResultados.getSelectedRow();
    
    if (fila != -1) {
        // Obtenemos los valores en objetos primero
        Object idFlujo = tblResultados.getValueAt(fila, 4);
        Object idChequeP = tblResultados.getValueAt(fila, 5);
        Object idChequeT = tblResultados.getValueAt(fila, 6);

        // Seteamos el texto, verificando que no sean nulos para que no escriba "null"
        txtIDFlujoMov.setText(idFlujo != null ? idFlujo.toString() : "");
        txtIdChequePropio.setText(idChequeP != null ? idChequeP.toString() : "");
        txtIdChequeTercero.setText(idChequeT != null ? idChequeT.toString() : "");
    }

    }

    private void inicializar() {

        con = new Conexion();
        daoFlujosMov = new DAOFlujosMov();
        txtIDFlujoMov.setText("");
        txtIDFlujoMov.setVisible(false);
        txtIdChequePropio.setText("");
        txtIdChequePropio.setVisible(false);
        txtIdChequeTercero.setText("");
        txtIdChequeTercero.setVisible(false);
        dateChooserFechaBuscar.setDate(null);

        tblResultados.setModel(modelTblResultado);
        tblResultados.getTableHeader().setReorderingAllowed(false);
    }

    private void llenarTablaResultados(Connection con) throws SQLException {
        String consulta = "SELECT mov.desc_movimiento, cue.nom_concepto, flujo.importe, "
                + "flujo.observaciones_mov, flujo.id_flujo_mov, flujo.id_cheque, flujo.id_cheque_tercero "
                + "FROM flujos_mov flujo "
                + "INNER JOIN movimiento mov ON (mov.id_movimiento = flujo.id_movimiento) "
                + "INNER JOIN cuentas cue ON (cue.id_cuenta = flujo.id_cuenta) "
                + "WHERE flujo.fecha_mov = ? "
                + "AND mov.desc_movimiento != 'Saldo Anterior' " // Excluye por nombre de movimiento
                + "AND cue.nom_concepto != 'Saldo Anterior'";    // Excluye por nombre de concepto

        int nroColumnas = 7;

        modelTblResultado.setRowCount(0); // Limpia la tabla antes de llenarla

        try (PreparedStatement ps = con.prepareStatement(consulta)) {
            ps.setDate(1, new java.sql.Date(dateChooserFechaBuscar.getDate().getTime()));

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    Object[] fila = new Object[nroColumnas];
                    for (int i = 0; i < nroColumnas; i++) {
                        fila[i] = rs.getObject(i + 1);
                    }
                    modelTblResultado.addRow(fila);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFecha = new javax.swing.JLabel();
        dateChooserFechaBuscar = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtIDFlujoMov = new javax.swing.JTextField();
        txtIdChequePropio = new javax.swing.JTextField();
        txtIdChequeTercero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja de Flujos Movimientos");

        lblFecha.setText("Fecha:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultados);

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIDFlujoMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdChequePropio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdChequeTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(dateChooserFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addComponent(panelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminar)
                    .addComponent(txtIDFlujoMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdChequePropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdChequeTercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        try {
            con.cerrarConexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al salir de la ventana, intente de nuevo.");
            this.dispose();
        }
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        limpiarTabla();

        if (dateChooserFechaBuscar.getDate() != null) {

            try {
                llenarTablaResultados(con.getConexion());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al cargar la tabla de Resultados, ingrese nuevamente.");
                this.dispose();
            }

        } else {

            JOptionPane.showMessageDialog(null, "Debe seleccionar una fecha.");
            dateChooserFechaBuscar.requestFocus();
            return;

        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblResultadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadosMousePressed
        txtIdChequePropio.setText("");
        txtIdChequeTercero.setText("");
        txtIDFlujoMov.setText("");
        seleccionarResultado();


    }//GEN-LAST:event_tblResultadosMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (txtIDFlujoMov.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Ocurrió un error, seleccione nuevamente el flujo movimiento a borrar de la tabla");
            return;

        } else {

            try {
                if (!txtIdChequePropio.getText().equals("") && !txtIdChequePropio.getText().equals("0")) {
                    // UPDATE EN CHEQUE PROPIO
                    PreparedStatement psPropio = con.getConexion().prepareStatement("UPDATE cheque_propio SET estado_cheque = 0, fecha_entrega_cheque = Null WHERE id_cheque = ?");
                    psPropio.setLong(1, Long.parseLong(txtIdChequePropio.getText()));
                    psPropio.executeUpdate();
                }

                if (!txtIdChequeTercero.getText().equals("") && !txtIdChequeTercero.getText().equals("0")) {
                    // UPDATE EN CHEQUE TERCERO
                    PreparedStatement psTercero = con.getConexion().prepareStatement("UPDATE cheque_tercero SET estado_cheque = 0, fecha_entrega_cheque = Null, id_cuenta_salida = Null, titular_destino = Null WHERE id_cheque = ?");
                    psTercero.setLong(1, Long.parseLong(txtIdChequeTercero.getText()));
                    psTercero.executeUpdate();
                }
                daoFlujosMov.eliminarFlujoMov(Long.parseLong(txtIDFlujoMov.getText()), con.getConexion());

                if (!txtIdChequePropio.equals("") && !txtIdChequePropio.equals("0")) {
                    //hacer update en cheque propio
                }

                if (!txtIdChequeTercero.equals("") && !txtIdChequeTercero.equals("0")) {
                    //hacer update en cheque tercero
                }

                JOptionPane.showMessageDialog(null, "Se eliminó el flujo movimiento correctamente");

                txtIDFlujoMov.setText("");

                dateChooserFechaBuscar.setDate(null);

                limpiarTabla();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar el flujo movimiento seleccionado, ingrese nuevamente");
                this.dispose();
            }

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmBajaFlujosMov().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser dateChooserFechaBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtIDFlujoMov;
    private javax.swing.JTextField txtIdChequePropio;
    private javax.swing.JTextField txtIdChequeTercero;
    // End of variables declaration//GEN-END:variables
}
