/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

import com.flujos.DAOs.DAOCheque;
import com.flujos.Entidades.Cheque;
import com.flujos.Entidades.ClienteProveedor;
import com.flujos.Entidades.Movimiento;
import com.flujos.Utilidades.Conexion;
import com.flujos.Utilidades.Utilidades;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author monse
 */
public class FrmCheques extends javax.swing.JFrame {

    private Conexion con;
    private DAOCheque daoCheque;

    DefaultComboBoxModel<String> modeloComboclienteProveedor = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> modeloComboclienteProveedorDestino = new DefaultComboBoxModel<>();

    /**
     * Creates new form FrmCheques
     */
    public FrmCheques() {
        try {
            initComponents();
            comboTitularCheque.setModel(modeloComboclienteProveedor);
            comboTitularDestino.setModel(modeloComboclienteProveedorDestino);

            inicializar();
        } catch (SQLException ex) {
            Utilidades.msg(null, "error al inicializar la ventana");
            this.dispose();
        }
    }

    private void inicializar() throws SQLException {

        TxtNumero.setText("");
        TxtImporteCheque.setText("");
        jDateFechaCobro.setDate(null);
        jComboTipoCheque.setSelectedIndex(0);
        jComboEstadoCheque.setSelectedIndex(0);
        TxtObservacionCheque.setText("");
        daoCheque = new DAOCheque();
        TxtIdCheque.setText("");
        TxtIdCheque.setVisible(false);
        TxtIdTitularCheque.setText("");
        TxtIdTitularCheque.setVisible(false);
        TxtIdTitularDestinoCheque.setText("");
        TxtIdTitularDestinoCheque.setVisible(false);
        con = new Conexion();

        jDateFechaEntrega.setDate(null);
        TxtUsoCheque.setText("");
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnLimpiar.setEnabled(true);
        daoCheque.llenarComboClienteProveedor(modeloComboclienteProveedor, con.getConexion());
        daoCheque.llenarComboClienteProveedorDestino(modeloComboclienteProveedorDestino, con.getConexion());
        comboTitularCheque.setSelectedIndex(0);
        comboTitularDestino.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNumero = new javax.swing.JTextField();
        lblNumCheque = new javax.swing.JLabel();
        lblImporteCheque = new javax.swing.JLabel();
        TxtImporteCheque = new javax.swing.JTextField();
        lblTipoCheque = new javax.swing.JLabel();
        lblEstadoDeCheque = new javax.swing.JLabel();
        lblObservacionCheque = new javax.swing.JLabel();
        TxtObservacionCheque = new javax.swing.JTextField();
        lblFechaEntrega = new javax.swing.JLabel();
        lblFechaCobro = new javax.swing.JLabel();
        lblTitularCheque = new javax.swing.JLabel();
        lblTitularDestino = new javax.swing.JLabel();
        lblUsoCheque = new javax.swing.JLabel();
        TxtUsoCheque = new javax.swing.JTextField();
        jDateFechaCobro = new com.toedter.calendar.JDateChooser();
        jDateFechaEntrega = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        TxtIdCheque = new javax.swing.JTextField();
        jComboEstadoCheque = new javax.swing.JComboBox<>();
        jComboTipoCheque = new javax.swing.JComboBox<>();
        comboTitularDestino = new javax.swing.JComboBox<>();
        comboTitularCheque = new javax.swing.JComboBox<>();
        TxtIdTitularCheque = new javax.swing.JTextField();
        TxtIdTitularDestinoCheque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumCheque.setText("Numero de cheque:");

        lblImporteCheque.setText("Importe de cheque:");

        lblTipoCheque.setText("Tipo de cheque");

        lblEstadoDeCheque.setText("Estado de cheque:");

        lblObservacionCheque.setText("Observacion del cheque:");

        lblFechaEntrega.setText("Fecha de entrega:");

        lblFechaCobro.setText("Fecha de cobro:");

        lblTitularCheque.setText("Titular del cheque:");

        lblTitularDestino.setText("Titular de destino:");

        lblUsoCheque.setText("Uso de cheque");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");

        btnEliminar.setText("Eliminar");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        TxtIdCheque.setEnabled(false);

        jComboEstadoCheque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Cobrado", "Por cobrar" }));

        jComboTipoCheque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Propio", "Terceros" }));

        comboTitularDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTitularDestinoItemStateChanged(evt);
            }
        });

        comboTitularCheque.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTitularChequeItemStateChanged(evt);
            }
        });

        TxtIdTitularCheque.setEnabled(false);

        TxtIdTitularDestinoCheque.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(TxtImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jDateFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblTipoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jComboTipoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblEstadoDeCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jComboEstadoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblObservacionCheque)
                        .addGap(71, 71, 71)
                        .addComponent(TxtObservacionCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblUsoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(TxtUsoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateFechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(comboTitularCheque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(lblTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(comboTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtIdTitularDestinoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIdTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIdCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(TxtIdCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNumCheque))
                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImporteCheque)
                    .addComponent(TxtImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFechaCobro))
                    .addComponent(jDateFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTipoCheque))
                    .addComponent(jComboTipoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblEstadoDeCheque))
                    .addComponent(jComboEstadoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacionCheque)
                    .addComponent(TxtObservacionCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaEntrega)
                    .addComponent(jDateFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitularCheque)
                    .addComponent(TxtIdTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitularDestino)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtIdTitularDestinoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsoCheque)
                    .addComponent(TxtUsoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (TxtNumero.getText().equals("")) {
            Utilidades.msg(null, "El numero del cheque no puede estar vacio");
            TxtNumero.requestFocus();
            return;
        }

        if (Utilidades.isNunInt(TxtNumero.getText()) && !(Integer.parseInt(TxtNumero.getText()) > 0)) {
            Utilidades.msg(null, "Numero incorrecto");
            TxtNumero.setText("");
            TxtNumero.requestFocus();
            return;
        }

        if (TxtImporteCheque.getText().equals("")) {
            Utilidades.msg(null, "El importe no puede estar vacio");
            TxtImporteCheque.requestFocus();
            return;
        }

        if (!Utilidades.isValidBigDecimal(TxtImporteCheque.getText())) {
            Utilidades.msg(null, "Importe incorrecto");
            TxtImporteCheque.setText("");
            TxtImporteCheque.requestFocus();
            return;
        }

        //EVALUAR FECHA DE COBRO TODO
        if (jComboTipoCheque.getSelectedItem().equals("--")) {
            Utilidades.msg(null, "El tipo de cheque no puede estar vacio");
            jComboTipoCheque.requestFocus();
            return;
        }

        if (jComboEstadoCheque.getSelectedItem().equals("--")) {
            Utilidades.msg(null, "El estado del cheque no puede estar vacio");
            jComboEstadoCheque.requestFocus();
            return;
        }

        //EVALUAR FECHA DE ENTREGA TODO
        if (Utilidades.existe(con.getConexion(), "SELECT (1) FROM cheque WHERE nro_cheque = " + Integer.parseInt(TxtNumero.getText()) + " ")) {
            Utilidades.msg(null, "No se puede ingresar porque el numero de cheque ya existe");
            TxtNumero.setText("");
            TxtIdCheque.setText("");
            TxtIdTitularCheque.setText("");
            TxtIdTitularDestinoCheque.setText("");

            TxtImporteCheque.setText("");
            jComboTipoCheque.setSelectedIndex(0);
            jComboEstadoCheque.setSelectedIndex(0);
            TxtObservacionCheque.setText("");
            comboTitularCheque.setSelectedIndex(0);
            comboTitularDestino.setSelectedIndex(0);
            TxtUsoCheque.setText("");
            jDateFechaCobro.setDate(null);
            jDateFechaEntrega.setDate(null);

        } else {
            try {
                Cheque cheque = new Cheque();
                cheque.setEstadoCheque(jComboEstadoCheque.getSelectedItem().equals("Cobrado") ? 1 : 0);
                cheque.setFechaCobroCheque(jDateFechaCobro.getDate());
                cheque.setTipoCheque(jComboTipoCheque.getSelectedItem().toString());
                cheque.setFechaEntregaCheque(jDateFechaEntrega.getDate());
                cheque.setImporteCheque(new BigDecimal(TxtImporteCheque.getText()));
                cheque.setNumCheque(Long.parseLong(TxtNumero.getText()));
                cheque.setObservacionCheque(TxtObservacionCheque.getText());

                //validar que no sea nulo o ""
                cheque.setTitularCheque((TxtIdTitularCheque.getText() != null && !TxtIdTitularCheque.getText().equals("")) ? Long.parseLong(TxtIdTitularCheque.getText()) : null);
                //validar que no sea nulo o ""
                cheque.setTitularDestino((TxtIdTitularDestinoCheque.getText() != null && !TxtIdTitularDestinoCheque.getText().equals("")) ? Long.parseLong(TxtIdTitularDestinoCheque.getText()) : null);
                cheque.setUsoCheque(TxtUsoCheque.getText());

                daoCheque.ingresarCheque(cheque, con.getConexion());
                Utilidades.msg(null, "Cheque ingresado correctamente");
                TxtNumero.setText("");
                TxtImporteCheque.setText("");
                jDateFechaCobro.setDate(null);
                jComboTipoCheque.setSelectedIndex(0);
                jComboEstadoCheque.setSelectedIndex(0);
                TxtObservacionCheque.setText("");
                jDateFechaEntrega.setDate(null);
                comboTitularCheque.setSelectedIndex(0);
                comboTitularDestino.setSelectedIndex(0);
                TxtUsoCheque.setText("");

            } catch (SQLException ex) {
                Utilidades.msg(null, "Error al ingresar el Cheque");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void comboTitularChequeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTitularChequeItemStateChanged
        TxtIdTitularCheque.setText("");
        try {
            String clienteProveedor = comboTitularCheque.getSelectedItem() != null ? comboTitularCheque.getSelectedItem().toString() : null;
            if (clienteProveedor == null || clienteProveedor.equals("--")) {
                TxtIdTitularCheque.setText("");
            } else {
                ClienteProveedor clienteProveedorSeleccionado = daoCheque.obtenerDatosClienteProveedor(clienteProveedor, con.getConexion());
                if (clienteProveedorSeleccionado != null) {
                    TxtIdTitularCheque.setText(String.valueOf(clienteProveedorSeleccionado.getIdClienteProveedor()));
                } else {
                    TxtIdTitularCheque.setText("");
                }
            }

        } catch (Exception e) {
            Utilidades.msg(null, "Se produjo un error en la seleccion del combo Titular Cheque, ingrese nuevamente");
            this.dispose();
        }
    }//GEN-LAST:event_comboTitularChequeItemStateChanged

    private void comboTitularDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTitularDestinoItemStateChanged
        TxtIdTitularDestinoCheque.setText("");
        try {
            String clienteProveedor = comboTitularDestino.getSelectedItem() != null ? comboTitularDestino.getSelectedItem().toString() : null;
            if (clienteProveedor == null || clienteProveedor.equals("--")) {
                TxtIdTitularDestinoCheque.setText("");
            } else {
                ClienteProveedor clienteProveedorSeleccionado = daoCheque.obtenerDatosClienteProveedor(clienteProveedor, con.getConexion());
                if (clienteProveedorSeleccionado != null) {
                    TxtIdTitularDestinoCheque.setText(String.valueOf(clienteProveedorSeleccionado.getIdClienteProveedor()));
                } else {
                    TxtIdTitularDestinoCheque.setText("");
                }
            }

        } catch (Exception e) {
            Utilidades.msg(null, "Se produjo un error en la seleccion del combo Titular Destino Cheque, ingrese nuevamente");
            this.dispose();
        }
    }//GEN-LAST:event_comboTitularDestinoItemStateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        btnAgregar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        String dato = JOptionPane.showInputDialog("Numero de cheque: ");

        if (dato != null && !dato.equals("") && Utilidades.isNumLong(dato) && Long.parseLong(dato) > 0) {
            Long datoLong = Long.valueOf(dato);
            Cheque cheque = daoCheque.obtenerDatos(datoLong, con.getConexion());

            if (cheque != null) {

                TxtIdCheque.setText(cheque.getIdCheque().toString());
                TxtNumero.setText(cheque.getNumCheque().toString());
                TxtImporteCheque.setText(cheque.getImporteCheque().toString());
                TxtIdTitularCheque.setText(cheque.getTitularCheque().toString());
                TxtIdTitularDestinoCheque.setText(cheque.getTitularDestino().toString());
                TxtUsoCheque.setText(cheque.getUsoCheque().toString());
                TxtObservacionCheque.setText(cheque.getObservacionCheque());
                jDateFechaCobro.setDate(cheque.getFechaCobroCheque());
                jDateFechaEntrega.setDate(cheque.getFechaEntregaCheque());
                jComboTipoCheque.setSelectedItem(cheque.getTipoCheque());
                cheque.setEstadoCheque(jComboEstadoCheque.getSelectedItem().equals("Cobrado") ? 1 : 0);
                jComboEstadoCheque.setSelectedItem(cheque.getEstadoCheque() == 1 ? "Cobrado" : "Por cobrar");
                comboTitularCheque.setSelectedItem(daoCheque.obtenerNombreRazonSocial(Long.parseLong(TxtIdTitularCheque.getText()), con.getConexion()));

                String nombreRazonSocial = daoCheque.obtenerNombreRazonSocial(Long.parseLong(TxtIdTitularDestinoCheque.getText()), con.getConexion());

                if (nombreRazonSocial != null) {
                    comboTitularDestino.setSelectedItem(nombreRazonSocial);
                } else {
                    comboTitularDestino.setSelectedItem("--");
                }

                //validar que no sea nulo o ""
                cheque.setUsoCheque(TxtUsoCheque.getText());

            } else {
                Utilidades.msg(null, "No existe el Cliente/Proveedor o se produjo un error");
                btnAgregar.setEnabled(true);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);

            }

        } else {
            Utilidades.msg(null, "Debe ingresar un número entero mayor a 0");
            btnAgregar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        TxtNumero.setText("");
        TxtImporteCheque.setText("");
        jDateFechaCobro.setDate(null);
        jComboTipoCheque.setSelectedIndex(0);
        jComboEstadoCheque.setSelectedIndex(0);
        TxtObservacionCheque.setText("");
        daoCheque = new DAOCheque();
        TxtIdCheque.setText("");
        TxtIdCheque.setVisible(false);
        TxtIdTitularCheque.setText("");
        TxtIdTitularCheque.setVisible(false);
        TxtIdTitularDestinoCheque.setText("");
        TxtIdTitularDestinoCheque.setVisible(false);

        jDateFechaEntrega.setDate(null);
        TxtUsoCheque.setText("");
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnLimpiar.setEnabled(true);
        comboTitularCheque.setSelectedIndex(0);
        comboTitularDestino.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCheques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtIdCheque;
    private javax.swing.JTextField TxtIdTitularCheque;
    private javax.swing.JTextField TxtIdTitularDestinoCheque;
    private javax.swing.JTextField TxtImporteCheque;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtObservacionCheque;
    private javax.swing.JTextField TxtUsoCheque;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> comboTitularCheque;
    private javax.swing.JComboBox<String> comboTitularDestino;
    private javax.swing.JComboBox<String> jComboEstadoCheque;
    private javax.swing.JComboBox<String> jComboTipoCheque;
    private com.toedter.calendar.JDateChooser jDateFechaCobro;
    private com.toedter.calendar.JDateChooser jDateFechaEntrega;
    private javax.swing.JLabel lblEstadoDeCheque;
    private javax.swing.JLabel lblFechaCobro;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblImporteCheque;
    private javax.swing.JLabel lblNumCheque;
    private javax.swing.JLabel lblObservacionCheque;
    private javax.swing.JLabel lblTipoCheque;
    private javax.swing.JLabel lblTitularCheque;
    private javax.swing.JLabel lblTitularDestino;
    private javax.swing.JLabel lblUsoCheque;
    // End of variables declaration//GEN-END:variables
}
