/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

import com.flujos.DAOs.DAOCheque;
import com.flujos.DAOs.DAOChequeTercero;
import com.flujos.DAOs.DAOCuenta;
import com.flujos.Entidades.ClienteProveedor;
import com.flujos.Entidades.Cuenta;
import com.flujos.Utilidades.Conexion;
import com.flujos.Utilidades.Utilidades;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author monse
 */
public class FrmConfirmacionSalidaChequeTercero extends javax.swing.JFrame {

    private Conexion con;
    DefaultComboBoxModel<String> modeloCuentaSalida = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> modeloTitularDestino = new DefaultComboBoxModel<>();

    private DAOCheque daoCheque;
    private DAOChequeTercero daoChequeTercero;
    private DAOCuenta daoCuenta;

    /**
     * Creates new form FrmConfirmacionSalidaChequeTercero
     */
    public FrmConfirmacionSalidaChequeTercero() {
        initComponents();
        comboCuentaSalida.setModel(modeloCuentaSalida);
        comboTitularDestino.setModel(modeloTitularDestino);
        inicializar();
    }

    private void inicializar() {
        try {
            con = new Conexion();

            con = new Conexion();
            daoCheque = new DAOCheque();
            daoCuenta = new DAOCuenta();
            daoChequeTercero = new DAOChequeTercero();

            TxtIdChequeTercero.setVisible(false);
            TxtIdCuenta.setVisible(false);
            TxtIdTitular.setVisible(false);

            daoCheque.llenarComboClienteProveedorDestino(modeloTitularDestino, con.getConexion());
            daoCuenta.llenarComboCuenta(modeloCuentaSalida, con.getConexion());

            comboCuentaSalida.setSelectedIndex(0);
            comboTitularDestino.setSelectedIndex(0);

            btnConfirmar.setEnabled(true);
            btnSalir.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(FrmConfirmacionSalidaChequeTercero.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public FrmConfirmacionSalidaChequeTercero(String id) {
        initComponents();
        comboCuentaSalida.setModel(modeloCuentaSalida);
        comboTitularDestino.setModel(modeloTitularDestino);

        inicializar();
        // Seteás el ID en el txtId DESTINO
        TxtIdChequeTercero.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtIdChequeTercero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboCuentaSalida = new javax.swing.JComboBox<>();
        TxtIdCuenta = new javax.swing.JTextField();
        TxtIdTitular = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTitularDestino = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONFIRMACION SALIDA CHEQUE TERCCEROS");

        jLabel1.setText("Cuenta Salida:");

        comboCuentaSalida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCuentaSalidaItemStateChanged(evt);
            }
        });

        jLabel2.setText("Titular Destino:");

        comboTitularDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTitularDestinoItemStateChanged(evt);
            }
        });

        btnConfirmar.setText("CONFIRMAR");

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addGap(103, 103, 103)
                        .addComponent(btnSalir)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCuentaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtIdTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(TxtIdChequeTercero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIdCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(TxtIdChequeTercero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCuentaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIdTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnSalir))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCuentaSalidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCuentaSalidaItemStateChanged

        TxtIdCuenta.setText("");
        try {
            String cuentaSalida = comboCuentaSalida.getSelectedItem() != null ? comboCuentaSalida.getSelectedItem().toString() : null;
            if (cuentaSalida == null || cuentaSalida.equals("--")) {
                TxtIdCuenta.setText("");
            } else {
                Cuenta cuentaEntradaSeleccionado = daoCuenta.obtenerDatos(cuentaSalida, con.getConexion());
                if (cuentaEntradaSeleccionado != null) {
                    TxtIdCuenta.setText(String.valueOf(cuentaEntradaSeleccionado.getIdCuenta()));
                } else {
                    TxtIdCuenta.setText("");
                }
            }

        } catch (Exception e) {
            Utilidades.msg(null, "Se produjo un error en la seleccion del combo cuenta salida, ingrese nuevamente");
            this.dispose();
        }

    }//GEN-LAST:event_comboCuentaSalidaItemStateChanged

    private void comboTitularDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTitularDestinoItemStateChanged

        TxtIdTitular.setText("");
        try {
            String clienteProveedor = comboTitularDestino.getSelectedItem() != null ? comboTitularDestino.getSelectedItem().toString() : null;
            if (clienteProveedor == null || clienteProveedor.equals("--")) {
                TxtIdTitular.setText("");
            } else {
                ClienteProveedor clienteProveedorSeleccionado = daoCheque.obtenerDatosClienteProveedor(clienteProveedor, con.getConexion());
                if (clienteProveedorSeleccionado != null) {
                    TxtIdTitular.setText(String.valueOf(clienteProveedorSeleccionado.getIdClienteProveedor()));
                } else {
                    TxtIdTitular.setText("");
                }
            }

        } catch (Exception e) {
            Utilidades.msg(null, "Se produjo un error en la seleccion del combo Titular Destino Cheque, ingrese nuevamente");
            this.dispose();
        }

    }//GEN-LAST:event_comboTitularDestinoItemStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        try {
            con.cerrarConexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al salir de la ventana, intente de nuevo.");
            this.dispose();
        }

        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmacionSalidaChequeTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmacionSalidaChequeTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmacionSalidaChequeTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfirmacionSalidaChequeTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfirmacionSalidaChequeTercero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtIdChequeTercero;
    private javax.swing.JTextField TxtIdCuenta;
    private javax.swing.JTextField TxtIdTitular;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboCuentaSalida;
    private javax.swing.JComboBox<String> comboTitularDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
