/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

import com.flujos.Utilidades.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sol
 */
public class FrmChequesPropiosEnviados extends javax.swing.JFrame {
    
        private Conexion con;
        private DefaultTableModel modelTblSalidasChequePropio;
        
    /**
     * Creates new form FrmChequesPropiosEnviados
     */
    public FrmChequesPropiosEnviados() {
        initComponents();
        crearModeloTabla();
        inicializar();
    }

    private void crearModeloTabla (){   
        modelTblSalidasChequePropio = (new DefaultTableModel (){
        
        @Override
        public boolean isCellEditable (int rowIndex, int colIndex ){
            return false;
        }
    });
 }

    private void limpiarTabla () {
        for (int i = 0; i < TblSalidasChequePropio.getRowCount (); i++){
            modelTblSalidasChequePropio.removeRow (i);
            i-= 1;
        }
 }

    
    private void inicializar (){
        con = new Conexion();
        TblSalidasChequePropio.setModel(modelTblSalidasChequePropio);
        TblSalidasChequePropio.getTableHeader().setReorderingAllowed(false);
        cargarDatos(con.getConexion());
    }
    
    private void cargarDatos (Connection con){
        modelTblSalidasChequePropio.setRowCount(0);
        modelTblSalidasChequePropio.setColumnCount(0);
        
String query = """
            SELECT
                ch.nro_cheque AS Cheque,
                ch.importe_cheque AS Importe,
                DATE_FORMAT(ch.fecha_cobro_cheque, '%d-%m-%Y') AS Fecha,
                ch.observacion_cheque AS Observacion,
                ti.nom_razon_social AS Destino,
                cu.nom_concepto AS Cuenta,
                ch.fecha_entrega_cheque AS Acreditacion
                FROM cheque_propio ch
                JOIN cliente_proveedores ti ON
                ti.id_cliente_proveedor = ch.titular_destino
                JOIN cuentas cu ON ch.id_cuenta_salida = cu.id_cuenta 
                WHERE ch.estado_cheque = 1
                ORDER BY ch.nro_cheque DESC;               
               """;

    try (
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query)) {

        ResultSetMetaData meta = rs.getMetaData();
    int columnas = meta.getColumnCount();

        // Configurar nombres de columnas
    for (int i = 1; i <= columnas; i++) {
        modelTblSalidasChequePropio.addColumn(meta.getColumnLabel(i));
    }

        // Cargar filas
    while (rs.next()) {
        Object[] fila = new Object[columnas];
        
    for (int i = 0; i < columnas; i++) {
        fila[i] = rs.getObject(i + 1);
    }
        modelTblSalidasChequePropio.addRow(fila);
    }

    }catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,
            "Error al cargar datos:\n ingrese nuevamente");
        this.dispose();

        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblSalidasChequePropio = new javax.swing.JTable();
        BtnSalir = new javax.swing.JButton();
        BtnSalir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHEQUES PROPIOS ACREDITADOS");

        TblSalidasChequePropio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblSalidasChequePropio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TblSalidasChequePropioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TblSalidasChequePropio);

        BtnSalir.setText("SALIR");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnSalir1.setText("SALIR");
        BtnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(BtnSalir1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(328, 328, 328)
                    .addComponent(BtnSalir)
                    .addContainerGap(305, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSalir1)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addComponent(BtnSalir)
                    .addContainerGap(148, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblSalidasChequePropioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblSalidasChequePropioMousePressed

    }//GEN-LAST:event_TblSalidasChequePropioMousePressed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        try {
            con.cerrarConexion();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al salir de la ventana, intente de nuevo.");
            this.dispose();

        }
        this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir1ActionPerformed
        try {
            con.cerrarConexion();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al salir de la ventana, intente de nuevo.");
            this.dispose();

        }
        this.dispose();
    }//GEN-LAST:event_BtnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChequesPropiosEnviados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChequesPropiosEnviados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChequesPropiosEnviados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChequesPropiosEnviados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChequesPropiosEnviados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSalir1;
    private javax.swing.JTable TblSalidasChequePropio;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
