/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

/**
 *
 * @author Ian
 */
public class FrmFlujoFondos extends javax.swing.JFrame {

    /**
     * Creates new form FrmFlujoFondos
     */
    public FrmFlujoFondos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarPrincipal = new javax.swing.JMenuBar();
        menuABMs = new javax.swing.JMenu();
        menuItemABMClienteProveedor = new javax.swing.JMenuItem();
        menuItemABMCuenta = new javax.swing.JMenuItem();
        menuItemABMMovimiento = new javax.swing.JMenuItem();
        menuCheque = new javax.swing.JMenu();
        menuItemCargaChequePropio = new javax.swing.JMenuItem();
        menuItemCargaChequeTerceros = new javax.swing.JMenuItem();
        menuItemSalidaPropio = new javax.swing.JMenuItem();
        menuItemSalidaTerceros = new javax.swing.JMenuItem();
        menuItemEnviadosTerceros = new javax.swing.JMenuItem();
        menuItemEnCartera = new javax.swing.JMenuItem();
        menuFlujos = new javax.swing.JMenu();
        menuItemFlujosMov = new javax.swing.JMenuItem();
        menuItemEliminarFlujoMov = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuItemFFnMensual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Flujo de Fondos");

        menuABMs.setText("ABMs");

        menuItemABMClienteProveedor.setText("Cliente/Proveedor");
        menuItemABMClienteProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemABMClienteProveedorActionPerformed(evt);
            }
        });
        menuABMs.add(menuItemABMClienteProveedor);

        menuItemABMCuenta.setText("Cuenta");
        menuItemABMCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemABMCuentaActionPerformed(evt);
            }
        });
        menuABMs.add(menuItemABMCuenta);

        menuItemABMMovimiento.setText("Movimiento");
        menuItemABMMovimiento.setActionCommand("");
        menuItemABMMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemABMMovimientoActionPerformed(evt);
            }
        });
        menuABMs.add(menuItemABMMovimiento);

        menuBarPrincipal.add(menuABMs);

        menuCheque.setText("Cheques");

        menuItemCargaChequePropio.setText("Carga cheques propios");
        menuItemCargaChequePropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCargaChequePropioActionPerformed(evt);
            }
        });
        menuCheque.add(menuItemCargaChequePropio);

        menuItemCargaChequeTerceros.setText("Carga cheques terceros");
        menuItemCargaChequeTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCargaChequeTercerosActionPerformed(evt);
            }
        });
        menuCheque.add(menuItemCargaChequeTerceros);

        menuItemSalidaPropio.setText("Salida Propios");
        menuItemSalidaPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalidaPropioActionPerformed(evt);
            }
        });
        menuCheque.add(menuItemSalidaPropio);

        menuItemSalidaTerceros.setText("Salida Terceros");
        menuItemSalidaTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalidaTercerosActionPerformed(evt);
            }
        });
        menuCheque.add(menuItemSalidaTerceros);

        menuItemEnviadosTerceros.setText("Cheques terceros enviados");
        menuItemEnviadosTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEnviadosTercerosActionPerformed(evt);
            }
        });
        menuCheque.add(menuItemEnviadosTerceros);

        menuItemEnCartera.setText("Cheques terceros en cartera");
        menuItemEnCartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEnCarteraActionPerformed(evt);
            }
        });
        menuCheque.add(menuItemEnCartera);

        menuBarPrincipal.add(menuCheque);

        menuFlujos.setText("Flujos");

        menuItemFlujosMov.setText("Flujos mov");
        menuItemFlujosMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFlujosMovActionPerformed(evt);
            }
        });
        menuFlujos.add(menuItemFlujosMov);

        menuItemEliminarFlujoMov.setText("Eliminar Flujo Movimiento");
        menuItemEliminarFlujoMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarFlujoMovActionPerformed(evt);
            }
        });
        menuFlujos.add(menuItemEliminarFlujoMov);

        menuBarPrincipal.add(menuFlujos);

        menuReportes.setText("Reportes");
        menuReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesActionPerformed(evt);
            }
        });

        menuItemFFnMensual.setText("FFn Mensuales");
        menuItemFFnMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFFnMensualActionPerformed(evt);
            }
        });
        menuReportes.add(menuItemFFnMensual);

        menuBarPrincipal.add(menuReportes);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemABMClienteProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemABMClienteProveedorActionPerformed
        FrmABMClienteProveedor menuABMClienteProveedor = new FrmABMClienteProveedor();
        menuABMClienteProveedor.setVisible(true);
        menuABMClienteProveedor.setLocationRelativeTo(null);

    }//GEN-LAST:event_menuItemABMClienteProveedorActionPerformed

    private void menuItemABMMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemABMMovimientoActionPerformed
        FrmABMMovimiento menuMovimiento = new FrmABMMovimiento();
        menuMovimiento.setVisible(true);
        menuMovimiento.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemABMMovimientoActionPerformed

    private void menuItemABMCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemABMCuentaActionPerformed
        FrmABMCuentas ventanaCuentas = new FrmABMCuentas();
        ventanaCuentas.setVisible(true);
        ventanaCuentas.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemABMCuentaActionPerformed

    private void menuItemCargaChequePropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCargaChequePropioActionPerformed

        FrmABMChequePropio ventanaPropios = new FrmABMChequePropio();
        ventanaPropios.setVisible(true);
        ventanaPropios.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemCargaChequePropioActionPerformed

    private void menuItemCargaChequeTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCargaChequeTercerosActionPerformed

        FrmABMChequeTerceros ventanaChequesTerceros = new FrmABMChequeTerceros();
        ventanaChequesTerceros.setVisible(true);
        ventanaChequesTerceros.setLocationRelativeTo(null);

    }//GEN-LAST:event_menuItemCargaChequeTercerosActionPerformed

    private void menuItemFlujosMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFlujosMovActionPerformed

        FrmFlujosMov ventanaFlujosMov = new FrmFlujosMov();
        ventanaFlujosMov.setVisible(true);
        ventanaFlujosMov.setLocationRelativeTo(null);

    }//GEN-LAST:event_menuItemFlujosMovActionPerformed

    private void menuItemEliminarFlujoMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarFlujoMovActionPerformed

        FrmBajaFlujosMov ventanaBajaFlujosMov = new FrmBajaFlujosMov();
        ventanaBajaFlujosMov.setVisible(true);
        ventanaBajaFlujosMov.setLocationRelativeTo(null);

    }//GEN-LAST:event_menuItemEliminarFlujoMovActionPerformed

    private void menuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesActionPerformed

        FrmReporteFFnMensuales ventanaFFnMensuales = new FrmReporteFFnMensuales();
        ventanaFFnMensuales.setVisible(true);
        ventanaFFnMensuales.setLocationRelativeTo(null);

    }//GEN-LAST:event_menuReportesActionPerformed

    private void menuItemSalidaPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalidaPropioActionPerformed
        FrmSalidaPropio ventanaFrmSalidaPropio = new FrmSalidaPropio();
        ventanaFrmSalidaPropio.setVisible(true);
        ventanaFrmSalidaPropio.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemSalidaPropioActionPerformed

    private void menuItemSalidaTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalidaTercerosActionPerformed
        FrmSalidaTerceros ventanaFrmSalidaTerceros = new FrmSalidaTerceros();
        ventanaFrmSalidaTerceros.setVisible(true);
        ventanaFrmSalidaTerceros.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemSalidaTercerosActionPerformed

    private void menuItemEnviadosTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEnviadosTercerosActionPerformed
        FrmChequesTerceroEnviados ventanaFrmEnviadosTerceros = new FrmChequesTerceroEnviados();
        ventanaFrmEnviadosTerceros.setVisible(true);
        ventanaFrmEnviadosTerceros.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemEnviadosTercerosActionPerformed

    private void menuItemEnCarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEnCarteraActionPerformed

        FrmChequeTerceroCartera ventanaFrmTercerosCartera = new FrmChequeTerceroCartera();
        ventanaFrmTercerosCartera.setVisible(true);
        ventanaFrmTercerosCartera.setLocationRelativeTo(null);

    }//GEN-LAST:event_menuItemEnCarteraActionPerformed

    private void menuItemFFnMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFFnMensualActionPerformed
        FrmReporteFFnMensuales ventanaReporteMensuales = new FrmReporteFFnMensuales();
        ventanaReporteMensuales.setVisible(true);
        ventanaReporteMensuales.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_menuItemFFnMensualActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFlujoFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFlujoFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFlujoFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFlujoFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFlujoFondos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuABMs;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuCheque;
    private javax.swing.JMenu menuFlujos;
    private javax.swing.JMenuItem menuItemABMClienteProveedor;
    private javax.swing.JMenuItem menuItemABMCuenta;
    private javax.swing.JMenuItem menuItemABMMovimiento;
    private javax.swing.JMenuItem menuItemCargaChequePropio;
    private javax.swing.JMenuItem menuItemCargaChequeTerceros;
    private javax.swing.JMenuItem menuItemEliminarFlujoMov;
    private javax.swing.JMenuItem menuItemEnCartera;
    private javax.swing.JMenuItem menuItemEnviadosTerceros;
    private javax.swing.JMenuItem menuItemFFnMensual;
    private javax.swing.JMenuItem menuItemFlujosMov;
    private javax.swing.JMenuItem menuItemSalidaPropio;
    private javax.swing.JMenuItem menuItemSalidaTerceros;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
