/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

import com.flujos.Utilidades.Conexion;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class FrmReporteFFnMensuales extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReporteFFnMensuales.class.getName());

    // 🔥 AGREGAR ESTA LÍNEA JUSTO AQUÍ
    private Conexion con = new Conexion();

    /**
     * Creates new form FrmReporteFFnMensuales
     */
    public FrmReporteFFnMensuales() {
        initComponents();
        Inicializar();
    }

    private void Inicializar() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // 🔒 BLOQUEAMOS LA EDICIÓN
            }
        };

        modelo.addColumn("Fecha");
        modelo.addColumn("Concepto");
        modelo.addColumn("Movimiento");
        modelo.addColumn("Ingreso");
        modelo.addColumn("Egreso");
        modelo.addColumn("Saldo");
        modelo.addColumn("Observaciones");

        tablaReporte.setModel(modelo);

        // 🔒 BLOQUEA REORDENAR COLUMNAS
        tablaReporte.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateChooserFecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Flujos movimientos mensuales");

        jLabel1.setText("fecha");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(dateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (dateChooserFecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tablaReporte.getModel();
        model.setRowCount(0);

        String fecha = new SimpleDateFormat("yyyy-MM-dd").format(dateChooserFecha.getDate());

        String sqlUpdateSaldo = "UPDATE flujos_mov SET fecha_mov = ?, "
                + "importe = (SELECT COALESCE(SUM(importe), 0) FROM (SELECT importe FROM flujos_mov WHERE fecha_mov < ? AND id_flujo_mov <> 1) AS sub) "
                + "WHERE id_flujo_mov = 1";

        String sqlSelect = """
    SELECT Fecha, Concepto, Movimiento, Ingreso, Egreso, Saldo, Observaciones
    FROM (
        SELECT 
            fecha_mov AS Fecha,
            cuentas.nom_concepto AS Concepto,
            movimiento.desc_movimiento AS Movimiento,
            CASE WHEN importe >= 0 THEN importe ELSE 0 END AS Ingreso,
            CASE WHEN importe < 0 THEN ABS(importe) ELSE 0 END AS Egreso,
            -- Cálculo del saldo acumulado incluyendo la fila 1
            SUM(importe) OVER (ORDER BY id_flujo_mov) AS Saldo,
            observaciones_mov AS Observaciones,
            id_flujo_mov
        FROM flujos_mov 
        JOIN cuentas ON flujos_mov.id_cuenta = cuentas.id_cuenta 
        JOIN movimiento ON flujos_mov.id_movimiento = movimiento.id_movimiento 
        -- Filtramos: O es el movimiento del día O es el ID 1 (Saldo Anterior)
        WHERE fecha_mov = ? OR id_flujo_mov = 1
    ) AS subconsulta
    ORDER BY id_flujo_mov ASC
    """;

        try {
            Connection conexion = con.getConexion();

            try (PreparedStatement psUpd = conexion.prepareStatement(sqlUpdateSaldo)) {
                psUpd.setString(1, fecha);
                psUpd.setString(2, fecha);
                psUpd.executeUpdate();
            }

            try (PreparedStatement psSel = conexion.prepareStatement(sqlSelect)) {
                psSel.setString(1, fecha);
                ResultSet rs = psSel.executeQuery();

                int columnas = rs.getMetaData().getColumnCount();

                SimpleDateFormat formatoVisual = new SimpleDateFormat("dd-MM-yyyy");

                while (rs.next()) {
                    Object[] fila = new Object[columnas];
                    for (int i = 0; i < columnas; i++) {
                        Object valor = rs.getObject(i + 1);

                        // --- CAMBIO AQUÍ: Si es la columna 0 (Fecha), formatear ---
                        if (i == 0 && valor != null) {
                            fila[i] = formatoVisual.format(valor);
                        } else {
                            fila[i] = valor;
                        }
                    }
                    model.addRow(fila);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al procesar reporte:\n" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReporteFFnMensuales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChooserFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReporte;
    // End of variables declaration//GEN-END:variables
}
